# Generated by Django 3.2 on 2021-04-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210410_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='liveImage',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
